import { cookieFor, SITE } from "./_v12lib.mjs";
import { readFileSync } from "node:fs";
const ids = JSON.parse(readFileSync("_v12ids.json", "utf8"));
const cookie = await cookieFor(ids.email);
const res = await fetch(`${SITE}/log?plan=${ids.plan}`, { headers: { cookie } });
const html = await res.text();
const isNew = html.includes("Required. The location and time are stamped");
const isOld = html.includes("Photo (optional)");
console.log(`${new Date().toISOString().slice(11,19)}  status=${res.status}  new build=${isNew}  old build=${isOld}`);
process.exit(isNew ? 0 : 1);
