import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The prototype in docs/ is a read-only behavioural reference, not app code.
    "docs/**",
    // Generated by the Cloudflare adapter: a bundled copy of the whole app and
    // its dependencies. Linting it means linting node_modules by another name.
    ".open-next/**",
    ".wrangler/**",
  ]),
]);

export default eslintConfig;
